apiVersion: v1
kind: Namespace
metadata:
  name: tqa
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: tqa
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: tqa
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
---
apiVersion: loadtest.jmeter.com/v1alpha1
kind: Jmeter
metadata:
  name: tqa-loadtest
  namespace: tqa
spec:
  # Add fields here
  slave_size: 3
  jmeter_master_image: kubernautslabs/jmeter_master:5.0
  jmeter_slave_image: kubernautslabs/jmeter_slave:5.0
  grafana_server_root: /
  grafana_service_type: ClusterIP
  grafana_image: grafana/grafana:6.1.6
  influxdb_image: influxdb:1.7
  grafana_install: "true"
  grafana_reporter_install: "true"
  grafana_reporter_image: kubernautslabs/jmeter-reporter:latest
  influxdb_install: "true"
